config/routes.rb
TestApp::Application.routes.draw do
  resources :comments

  resources :welcomes

  resources :events

  resources :programs

  root to: 'welcomes#index'  

  

end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :set_welcome, only: [:show, :edit, :update, :destroy]

  # GET /welcomes
  # GET /welcomes.json
  def index
    @welcomes = Welcome.all
  end

  # GET /welcomes/1
  # GET /welcomes/1.json
  def show
  end

  # GET /welcomes/new
  def new
    @welcome = Welcome.new
  end

  # GET /welcomes/1/edit
  def edit
  end

  # POST /welcomes
  # POST /welcomes.json
  def create
    @welcome = Welcome.new(welcome_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to @welcome, notice: 'Welcome was successfully created.' }
        format.json { render action: 'show', status: :created, location: @welcome }
      else
        format.html { render action: 'new' }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomes/1
  # PATCH/PUT /welcomes/1.json
  def update
    respond_to do |format|
      if @welcome.update(welcome_params)
        format.html { redirect_to @welcome, notice: 'Welcome was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomes/1
  # DELETE /welcomes/1.json
  def destroy
    @welcome.destroy
    respond_to do |format|
      format.html { redirect_to welcomes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def welcome_params
      params[:welcome]
    end
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/welcomes/_form.html.erb
<%= form_for(@welcome) do |f| %>
  <% if @welcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@welcome.errors.count, "error") %> prohibited this welcome from being saved:</h2>

      <ul>
      <% @welcome.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/welcomes/edit.html.erb
<h1>Editing welcome</h1>

<%= render 'form' %>

<%= link_to 'Show', @welcome %> |
<%= link_to 'Back', welcomes_path %>

app/views/welcomes/index.html.erb
<h3>Welcome to DIASPARK website</h3>

<b>About us:</b> 

 Diaspark follows a 360-degree business approach. Our innovative technology solutions bring in efficiencies and empower our clients with the most advanced technologies to ensure optimal ROI.

This approach is backed by our 16years of successful and extensive solution-implementation experience with best-of-the-breed customers ranging from Billion-dollar enterprises, Mid-sized and SMEs. Our quality processes are endorsed by the industry's leading certification standard SEI-CMMI.

The 650+ members of the Diaspark family are united by the organization's shared values and an unwavering commitment to quality.<br>


<br><b>Address:</b>
         <br>402,block-A new rani bagh
             khandwa road, indore.</br>

<br><b>Contact Us</b></br>

    U.S. -Edison- Corporate Office
    Corporate Office
    200 Metroplex Drive, Edison, NJ, 08817
    Tel: +1 732 248 8333 Ext. 6740
    Toll Free : - 1-800-900-2200
    Fax: +1 732 248 8334</br>
    </br>U.S. - New York – Regional office
    333, 7th Avenue, New York, NY, 10001
    Tel: +1 212 972 2740
    Toll Free : - 1-800-900-2200
    Fax: +1 732 248 8334</br>
    </br>India – Indore – Global Delivery Centre I
    Labh Ganga Building
    582, M.G. Road
    Indore – 452003
    Madhya Pradesh, India
    Tel: +91 731 4756000, +91 731 4273300
    Fax: +91 731 2548555</br>
    </br>Sales Enquiry : +91 731 4273300
    India - Pune - Global Delivery Centre II
    Unit # 103, Level 1, Pentagon Tower P-4, Magarpatta City,
    Hadapsar, Pune - 411013
    Maharashtra, India
    Tel: +91 (0) 20 32405866</br>


<h2>Enjoy various cultural activies at DiaSpark</h2></br>
        
      <%= link_to 'Programs', programs_path %></br>

      <%= link_to 'Events', events_path %></br>

app/views/welcomes/new.html.erb
<h1>New welcome</h1>

<%= render 'form' %>

<%= link_to 'Back', welcomes_path %>

app/views/welcomes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_welcome_path(@welcome) %> |
<%= link_to 'Back', welcomes_path %>